AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ROLE:
    Type: String

Resources:
  octankNewsTranslateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: octankNewsTranslateLambda
      Description: Process text to speach and translation of news articles.
      Handler: index.go
      CodeUri: ./index.py
      Runtime: python3.7
      MemorySize: 128
      Timeout: 10
      Role: !Ref ROLE
      Environment:
        Variables:
          BUCK_SRC: "content-production-octank-news"
          BUCK_TAR: "octank-news"
          VOICE_FR: "Celine"
          VOICE_EN: "Emma"
          INTRO_EN: "Hello, this is a news announcement from Octank News. "
          INTRO_FR: "Bonjour, ceci est une annonce de nouvelles d'Octank News. "
          OUTPUT_PATH_AUDIO: "audio/<LANG>/headline_<FILE>.mp3"
          OUTPUT_PATH_JSON: "content/<LANG>/headline_<FILE>.json"
